version: '3.8'

services: 
  app:
    container_name: web
    build: ./docker/web
    ports: 
        - 8080:8080
    volumes: 
        - ./server:/app:cached
    tty: true
    stdin_open: true
    privileged: true
    command: sh -c "npm run dev"